version: '3'
services:
  barinade-jenkins:
    image: barinade/jenkins:lts-jdk11
    ports:
      - "10090:8080"
      - "10190:50000"
    volumes:
      - /barinade/volumes/jenkins:/var/jenkins_home
  barinade-nexus:
    image: sonatype/nexus3
    ports:
      - "10091:8081"
    volumes:
      - /barinade/volumes/nexus:/nexus-data
