version: '3'
services:
  barinade-jenkins:
    image: barinade/jenkins:lts-jdk11
    ports:
      - "10090:8080"
      - "10190:50000"
    volumes:
      - /barinade/volumes/jenkins:/var/jenkins_home
  barinade-nexus:
    image: sonatype/nexus3
    ports:
      - "10091:8081"
    volumes:
      - /barinade/volumes/nexus:/nexus-data
  irc-test:
    image: inspircd/inspircd-docker
    ports:
      - "10050:6667"
      - "10051:6697"
      - "10052:7000"
      - "10053:7001"
    volumes:
      - /barinade/volumes/irc/server/test:/inspircd/conf/
    environment:
      - INSP_NET_NAME=Project Barinade Test IRC
      - INSP_ADMIN_NAME=scaramanga
      - INSP_ADMIN_NICK=scaramanga
      - INSP_ADMIN_EMAIL=scaramangado@gmail.com
      - INSP_CONNECT_PASSWORD=a45e2df6b898e7c4fb895fd86ed479b7e158eb71246fae17e5f0b55e217d5bdc
      - INSP_CONNECT_HASH=sha256
      - INSP_OPER_NAME=scaramanga
      - INSP_OPER_PASSWORD_HASH=e6c6d3d1bd62ad6aed666d5e6776b41f1dd6d219fc6bbb2394f903c11172968e
      - INSP_OPER_SSLONLY=no