version: '3.9'
services:
  bot:
    image: ghcr.io/ootbingo/barinade-bot/bot:prod
    restart: unless-stopped
    volumes:
      - ~/docker-volumes/barinade-prod/etc/barinade:/etc/barinade
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ~/docker-volumes/barinade-prod/db:/var/lib/postgresql/data
      - ~/projects/barinade-infrastructure/prod:/barinade/barinade-infrastructure/prod
    ports:
      - "10110:5432"
    environment:
      - POSTGRES_DB=BARINADE
      - POSTGRES_USER=scaramanga
      - POSTGRES_PASSWORD_FILE=/barinade/barinade-infrastructure/prod/postgres_pwd
      
